[project]
name = "logic CODER-220"
version = "0.1.0"
authors = [
  { name="-------", email="-------" },
]
description = "A small package with logical operators"
readme = "README.pdf"
requires-python = ">=any"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/CODER-220/Logic-Library"
Issues = "https://github.com/CODER-220/Logic-Library/issues"
